//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public int Id { get; set; }
        public string Ten_MaGiamGia { get; set; }
        public Nullable<decimal> Tien { get; set; }
    }
}
