//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietDatHang = new HashSet<ChiTietDatHang>();
        }
    
        public int Id_MonAn { get; set; }
        public string Ten_MonAn { get; set; }
        public Nullable<decimal> GiaBanMoi_MonAn { get; set; }
        public Nullable<decimal> GiaBanCu_MonAn { get; set; }
        public string ThanhPhan_MonAn { get; set; }
        public string MoTa_MonAn { get; set; }
        public Nullable<int> Id_ThucDon { get; set; }
        public string AnhChinh_MonAn { get; set; }
        public string AnhPhu1_MonAn { get; set; }
        public string AnhPhu2_MonAn { get; set; }
        public string AnhPhu3_MonAn { get; set; }
        public Nullable<int> Id_LoaiMon { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> Id_GiamGiaSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHang { get; set; }
        public virtual GiamGiaSP GiamGiaSP { get; set; }
        public virtual LoaiMon LoaiMon { get; set; }
        public virtual ThucDon ThucDon { get; set; }
    }
}
